# Generated by Django 5.2 on 2025-04-30 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=45)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=11)),
                ('lotacao', models.CharField(blank=True, max_length=45, null=True)),
                ('matricula', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('tipo_usuario', models.CharField(help_text='Haverá uma hierarquia de acessos', max_length=15)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('idInscricao', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.CharField(db_column='IdEvento', max_length=45)),
                ('usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'inscricoes',
            },
        ),
    ]
