# Generated by Django 5.2.2 on 2025-06-26 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'Cliente')], default='cliente', help_text='Haverá uma hierarquia de acessos', max_length=15),
        ),
    ]
