# Generated by Django 5.2 on 2025-05-01 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idUsuario',
            new_name='id_usuario',
        ),
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
