# Generated by Django 5.2.1 on 2025-05-20 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=45)),
                ('ambiente', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=500)),
                ('palestrantes', models.CharField(max_length=45)),
                ('checkin_code', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
                ('total_inscritos', models.IntegerField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.CharField(db_column='id_evento', max_length=45)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inscricoes',
            },
        ),
    ]
