# Generated by Django 5.2 on 2025-05-01 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_rename_idusuario_usuario_id_usuario_delete_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id_inscricao', models.AutoField(primary_key=True, serialize=False)),
                ('id_evento', models.CharField(db_column='id_evento', max_length=45)),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
            options={
                'db_table': 'inscricoes',
            },
        ),
    ]
