# Generated by Django 5.2 on 2025-05-05 23:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('users', '0002_rename_idusuario_usuario_id_usuario_delete_inscricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=45)),
                ('ambiente', models.CharField(max_length=45)),
                ('descricao', models.CharField(max_length=500)),
                ('palestrantes', models.CharField(max_length=45)),
                ('checkin_code', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(max_length=45)),
                ('total_inscritos', models.IntegerField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usuario')),
            ],
        ),
    ]
