# Generated by Django 5.2 on 2025-05-06 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='criadoEm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inscricao',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
