# Generated by Django 5.2.1 on 2025-06-22 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_eventos_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='id',
        ),
        migrations.AddField(
            model_name='eventos',
            name='id_evento',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='id_evento',
            field=models.ForeignKey(db_column='id_evento', on_delete=django.db.models.deletion.CASCADE, to='event.eventos'),
        ),
    ]
