# Generated by Django 5.2 on 2025-05-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_inscricao_criadoem_inscricao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
