# Generated by Django 5.2.2 on 2025-06-26 23:38

import uuid
from django.db import migrations, models

def generate_events_checkin_code(apps, schema_editor):
    Events = apps.get_model('event', 'Eventos')

    for evento in Events.objects.all():
        evento.checkin_code = uuid.uuid4()
        evento.save()

class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_eventos_id_eventos_id_evento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='checkin_code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='descricao',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='total_inscritos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada'), ('validada', 'Validada'), ('expirada', 'Expirada')], default='ativa', max_length=10),
        ),
        migrations.RunPython(generate_events_checkin_code)
    ]
