# Generated by Django 5.2.1 on 2025-05-27 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acesso',
            fields=[
                ('idAcesso', models.AutoField(primary_key=True, serialize=False)),
                ('Ambiente', models.CharField(max_length=45)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'acesso',
            },
        ),
    ]
